### 
POST http://localhost:8080/auth/kakao
Content-Type: application/x-www-form-urlencoded

{
  "grant_type": "authorization_code",
  "clientID": "e354970c3c53ec24635b443a72761cfd",
  "redirectUri": "http://localhost:3000/auth",
  "code": "Xop6yAM00uvfaJa3pRzTWpm9732TPG0z4GB4eAO8xEPad0y9ZPcjbQAAAAQKKiWQAAABj49spiV-jFVpBnvzXw"
}         

### 
GET  http://localhost:8080/school/list 

###
GET http://localhost:8080/school/list/search?schoolName=가  

### 
GET http://localhost:8080/major/list 



### 
POST http://localhost:8080/portpolio/save
Content-Type: application/json

{
 "portpolioId": "test"
}         

###
GET http://localhost:8080/user/findByUserTableID
Content-Type: application/json

{
 "users_table_id": "664c010d5b425b03e616e583"
}         


###  
GET http://localhost:8080/test
Content-Type: application/json


